paths:
  ca_logs_full_path: "C:/CA/exported_ca_logs.csv"
  ca_logs_pruned_path: "synthetic_ca_logs_training.csv"
  ca_logs_detection_path: "synthetic_ca_logs_detection.csv"
  model_output_path: "certifeye_model.joblib"
  params_output_path: "certifeye_params.pkl"

known_abuse_request_ids:
- 10604
- 16134
- 21674
- 22081
- 25433
- 27683
- 29959
known_good_request_ids: []

privileged_keywords:
- Admin
- Administrator
- Root
- System
- Service
- Backup
- Security
- DomainAdmin
- EnterpriseAdmin
vulnerable_templates:
- AdminCertificate
- DomainControllerCertificate
- CodeSigningCertificate
- ESC1
templates_requiring_approval: []

authorized_client_auth_users: []

algorithm: 'xgboost'  # Options: 'random_forest', 'xgboost'

training_mode: "supervised"

smtp:
  server: 'smtp.yourdomain.com'
  port: 587
  username: 'alert@yourdomain.com'
  password: 'your_password'  # Secure this appropriately
  sender_email: 'alert@yourdomain.com'

validity_threshold: 730           # Validity threshold in days
request_volume_threshold: 50      # Request volume threshold
classification_threshold: 0.561    # Classification threshold

off_hours_start: 22               # Off-hours start hour (22:00 / 10 PM)
off_hours_end: 6                  # Off-hours end hour (6:00 AM)
