paths:
  ca_logs_full_path: "C:/CA/exported_ca_logs.csv"             # Path to your actual CA logs
  ca_logs_pruned_path: "synthetic_ca_logs_training.csv"       # Path for pruned logs (if pruning is used)
  ca_logs_detection_path: "synthetic_ca_logs_detection.csv"   # Path for new CA logs to be analyzed for potential abuse
  model_output_path: "certifeye_model.joblib"                 # Path where the trained model will be saved
  scaler_output_path: "certifeye_scaler.joblib"               # Path where the scaler will be saved
  anomaly_model_path: "certifeye_isolation_forest.joblib"     # Path where the Isolation Forest model will be saved
  detection_results_path: "detection_results.csv"             # Path where detection results will be savedexit
  params_output_path: "certifeye_params.pkl"

# Known Request IDs
known_abuse_request_ids:
- 10938
- 11265
- 12478
- 14533
- 16052
- 16700
- 17125
- 17580
- 18953
- 18998
- 19804
- 20680
- 21404
- 22944
- 23187
- 23284
- 24213
- 25746
- 26817
- 27193
known_good_request_ids: []
privileged_keywords:
- Admin
- Administrator
- Root
- System
- Service
- Backup
- Security
- DomainAdmin
- EnterpriseAdmin
vulnerable_templates:
- AdminCertificate
- DomainControllerCertificate
- CodeSigningCertificate
- ESC1
detection:
  classification_threshold: 0.5  # Unified detection threshold
  validity_threshold: 730         # Single validity threshold definition

synthetic:
  defaults:
    train_records: 1000
    train_abuses: 5
    train_anomalies: 10
    detect_records: 5000
    detect_abuses: 5 
    detect_anomalies: 10
  normal_validity_days:
    mean: 730    # 2 years
    std_dev: 0  # ~1 month variation
  business_hours:
    start: 8     # 8 AM
    end: 18      # 6 PM
    days: [0, 1, 2, 3, 4] # Mon-Fri (Monday=0)
  domain_name: "contoso.com"
  internal_domain: "intra.contoso.local"
  departments:
  - Sales
  - Marketing
  - Engineering
  - HR
  - Finance
  - IT
  - Legal
  - Operations
  certificate_templates:
    UserCertificate: ["Client Authentication", "Secure Email"]
    MachineCertificate: ["Client Authentication", "Server Authentication"]
    AdminCertificate: ["Client Authentication", "Any Purpose"]
    ServerCertificate: ["Server Authentication"]
    EncryptionCertificate: ["Secure Email"]
    VPNCertificate: ["Client Authentication"]
    EmailCertificate: ["Secure Email"]
    SMIMECertificate: ["Secure Email"]
    CodeSigningCertificate: ["Code Signing"]
    DomainControllerCertificate: ["Client Authentication", "Server Authentication"]
    UnknownTemplate: ["UnknownUsage"]
  abuse_ekus:
  - Client Authentication
  - Smart Card Logon
  - PKINIT Client Authentication
  - Any Purpose
  - SubCA
  - Code Signing
  - UnknownUsage

templates_requiring_approval:
authorized_client_auth_users:
- elizabeth.johnson
- taylor.roberts
- robert.henson
- kim.mcdonald
- calvin.valdez
authorized_developers:
- steven.williams
- lisa.vargas
- kathryn.martinez
- james.smith
- philip.valenzuela
authorized_ca_operators:
- caoperator1
- caoperator2
  # Users authorized to request CA certificates

# Suspicious EKUs
suspicious_ekus:
- 'Any Purpose'
- 'Certificate Request Agent'
- 'Code Signing'

# Authorized Users for Suspicious EKUs
authorized_users_for_suspicious_ekus:
- alice.admin
- bob.caop
  # Users authorized to request certificates with suspicious EKUs

# Threshold Configurations
validity_threshold: 730
request_volume_threshold: 50
classification_threshold: 0.631
off_hours_start: 22
off_hours_end: 6
max_historical_days: 90
validity_zscore_threshold: 2.5  # Sensitivity (default=2.5 = ~99th percentile)
# Additional checks
enable_zscore_checks: true  # Master switch
enable_esc_checks: true
enable_suspicious_eku_checks: true
enable_privilege_escalation_checks: true
enable_template_misuse_checks: true
synthetic_data:
  enable_auto_config_updates: true
  flag_off_hours_as_abuse: false           # Set to true if off-hours requests should be flagged as abuse
  benign_anomaly_probability: 0.05         # Probability of introducing benign anomalies in synthetic data
  subtle_anomalies: true
  anomaly_combinations:
  - valid_template_with_suspicious_eku
  - mismatched_san_and_requester

# SMTP Configuration for Alerts
smtp:
  enabled: false  # Must be explicitly set
  server: 'smtp.office365.com'
  port: 587
  username: 'security-alerts@contoso.com'
  password: '${SMTP_PASSWORD}'  # Use env variable in real deployment
  sender_email: 'certifeye-alerts@contoso.com'

# Algorithm and Training Mode
algorithm: 'xgboost'
training_mode: 'supervised'
valid_templates:
- UserCertificate
- MachineCertificate

pruning:
  default_sample_size: 3000

